# https://github.com/seed-rs/seed/tree/master/examples/server_integration

[tasks.build]
description = "Build frontend and backend"
clear = true
workspace = false
dependencies = ["build_frontend", "build_backend"]

[tasks.build_release]
extend = "build"
description = "Build frontend and backend in release mode"
dependencies = ["build_frontend_release", "build_backend_release"]

[tasks.build_frontend]
description = "Build frontend"
workspace = false
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "frontend", "--target", "web", "--out-name", "package", "--dev"]

[tasks.build_frontend_release]
extend = "build_frontend"
description = "Build frontend in release mode"
args = ["build", "frontend", "--target", "web", "--out-name", "package", "--release"]

[tasks.build_backend]
description = "Build backend"
workspace = false
command = "cargo"
args = ["build", "--package", "backend"]

[tasks.build_backend_release]
extend = "build_backend"
description = "Build backend in release mode"
args = ["build", "--package", "backend", "--release"]

[tasks.start]
description = "Build and start Actix backend with frontend on port 8000"
workspace = false
command = "cargo"
args = ["run", "--package", "backend"]
dependencies = ["build"]

[tasks.start_release]
extend = "start"
description = "Build and start Actix backend with frontend on port 8000 in release mode"
args = ["run", "--package", "backend", "--release"]
dependencies = ["build_release"]
